; === Upload & Post Size ===
upload_max_filesize = 20M
post_max_size = 25M

; === Memory & Execution ===
memory_limit = 512M
max_execution_time = 120

; === File Handling ===
max_file_uploads = 20

; === Error Reporting (opsional, buat debug) ===
display_errors = On
error_reporting = E_ALL
